In container posix semantics
msys2/Cygwin pull request #141
Opened 2023-03-07 14:07 UTC by YO4

#59 complains that remove does not work in docker volume folder.
That seems to mounted folder does not support *_POSIX_SEMANTICS functions in hyper-v container.
https://ci.appveyor.com/project/YO4/test-msys2-in-container/builds/46432262

Since it is unclear how to determine in advance whether posix semantics will work, fall back to the conventional method when an error occurs.

Functions affected are unlink(), rename(), and their derivatives.

2023-03-07 18:00 UTC, jeremyd2019 commented
I assume this issue also exists in upstream Cygwin.  It might make sense to send this patch upstream to cygwin-patches@cygwin.com and get their opinions/ideas, and hopefully get something applied there first.

2023-03-08 09:51 UTC, AJDurant commented
> Since it is unclear how to determine in advance whether posix semantics will work, fall back to the conventional method when an error occurs.

This is the thing I was stuck on, your solution seems neat to me.

2023-03-17 14:53 UTC, YO4 commented
I updated test https://ci.appveyor.com/project/YO4/test-msys2-in-container/builds/46532757
and posted patches to cygwin-patches.

2023-03-20 12:47 UTC, dscho commented
For lurkers, the Cygwin contribution can be seen [here](https://inbox.sourceware.org/cygwin-patches/20230317144346.871-1-ysno@ac.auone-net.jp/#t).

2023-03-24 14:17 UTC, YO4 commented
Now this patches are merged into upstream/master, 527dd1b 7666e24 87ab6c7
And they added making a decision in advance with FILE_SUPPORTS_OPEN_BY_FILE_ID fe2545e

2023-03-27 12:03 UTC, dscho commented
@YO4 personally, I'd love to see the changes backported early into the MSYS2 runtime (once the jury has decided on `FILE_SUPPORTS_OPEN_BY_FILE_ID` that is, and the patches have stabilized).

2023-04-14 14:55 UTC, YO4 commented
Hmmm, I saw https://github.com/msys2/msys2-runtime/tags and mistakenly assumed that msys2-runtime would not be updated until cygwin's next release.
If msys2-runtime can be released with a new pkgrel before the next release of cygwin, I would like to see this PR merged.
At this time, this patch does not include a decision on ```FILE_SUPPORTS_OPEN_BY_FILE_ID```, but it is preferable to be able to complete the process with a retry rather than have it fail.

2023-05-26 08:32 UTC, dscho commented
> If msys2-runtime can be released with a new pkgrel before the next release of cygwin, I would like to see this PR merged.

I see that the upstream version is slightly different: https://github.com/msys2/msys2-runtime/commit/87ab6c7b26bf3c925183d7e439985db070b03b39#diff-bf890865130314cb545fec4788e41d9daa5dd8832a21435c6556619d5578a8aaL740-R744 does not look like https://github.com/msys2/msys2-runtime/pull/141/commits/749d3a29aeb3dbc6b8df68fec66cd6dc2a452f18#diff-bf890865130314cb545fec4788e41d9daa5dd8832a21435c6556619d5578a8aaR739-R741

Other than that, I am totally in favor of merging it and incrementing the `pkgrel`.

2023-07-10 10:16 UTC, AJDurant requested changes
@YO4 can you make the change that @dscho mentioned in https://github.com/msys2/msys2-runtime/pull/141#issuecomment-1564013010 so this can get merged?

2023-07-10 10:16 UTC, AJDurant commented on winsup/cygwin/syscalls.cc
> +                    pc.get_nt_native_path (), status);
```suggestion
        {
          debug_printf ("NtSetInformationFile returns %y "
                        "with posix semantics. Disable it and retry.", status);
          goto out;
        }
```

2026-07-29 15:27 UTC, dscho commented
> Now this patches are merged into upstream/master, [527dd1b](https://github.com/msys2/msys2-runtime/commit/527dd1b407e7d74037a19aed6e25aa36578da2f7) [7666e24](https://github.com/msys2/msys2-runtime/commit/7666e248dd08ba96c12748fc4781388f57671ae5) [87ab6c7](https://github.com/msys2/msys2-runtime/commit/87ab6c7b26bf3c925183d7e439985db070b03b39) And they added making a decision in advance with FILE_SUPPORTS_OPEN_BY_FILE_ID [fe2545e](https://github.com/msys2/msys2-runtime/commit/fe2545e9faaf4bf9586f61a7b83d5cb5af501194)

In the meantime, we're on the Cygwin v3.6.* train, which has those commits (even v3.5.0 already had them). So I'll close this here PR as addressed.

2026-07-29 15:27 UTC, closed without merging