Update to 3.5.4
msys2/Cygwin pull request #225
Opened 2024-08-25 13:38 UTC by lazka

2024-08-26 07:59 UTC, dscho requested changes
Thank you! Looks good except for a very minor nit.

2024-08-26 07:59 UTC, dscho commented on winsup/cygwin/environ.cc
> +  {NL ("MSYS_DEBUG="), false, true, NULL},
This hunk probably wanted to be dropped, as per https://github.com/msys2/msys2-runtime/commit/38020a7e0e6a105b9d4bc25e745286014a36d17d#diff-58d9d402d5db25b56c1a6d36aaa6b8af563f298144a471eaa82b23053bb96580L1015-R1015.

2024-08-27 14:45 UTC, dscho commented on winsup/cygwin/environ.cc
> +  {NL ("MSYS_DEBUG="), false, true, NULL},
Like [this](https://github.com/msys2/msys2-runtime/pull/225/commits/9b4cf2936a50d91759cc60a2ef13e51731a9ca5a).

2024-08-27 14:58 UTC, dscho approved these changes

2024-08-27 15:38 UTC, dscho commented
I force-pushed after rebasing.

<details><summary>Range-diff</summary>



* 1:  cbacf21a49 !  1:  f16038529a Add functionality for changing OS name via MSYSTEM environment variables.

   ``````diff
   @@ winsup/cygwin/environ.cc: win32env_to_cygenv (PWCHAR rawenv, bool posify)
           if (*eq && posify)
             posify_maybe (envp + i, *++eq ? eq : --eq, tmpbuf);
           debug_printf ("%p: %s", envp[i], envp[i]);
   -@@ winsup/cygwin/environ.cc: struct spenv
   - static NO_COPY spenv spenvs[] =
   - {
   - #ifdef DEBUGGING
   --  {NL ("CYGWIN_DEBUG="), false, true, NULL},
   -+  {NL ("MSYS_DEBUG="), false, true, NULL},
   - #endif
   -   {NL ("HOMEDRIVE="), false, false, &cygheap_user::env_homedrive},
   +@@ winsup/cygwin/environ.cc: static NO_COPY spenv spenvs[] =
       {NL ("HOMEPATH="), false, false, &cygheap_user::env_homepath},
       {NL ("LOGONSERVER="), false, false, &cygheap_user::env_logsrv},
       {NL ("PATH="), false, true, NULL},
   ``````

* 2:  c0adae6e38 =  2:  6393488c9d - Move root to /usr. - Change sorting mount points. - By default mount without ACLs. - Can read /etc/fstab with short mount point format.
* 3:  aa6e313b9a =  3:  06ea20e4ec Instead of creating Cygwin symlinks, use deep copy by default
* 4:  55cc41353d =  4:  222fd37c0b Automatically rewrite TERM=msys to TERM=cygwin
* 5:  e7d9d442ce =  5:  41e8ada0d1 Do not convert environment for strace
* 6:  a1e28fb96a =  6:  766e55c1be strace.cc: Don't set MSYS=noglob
* 7:  5c3c66a4ec =  7:  4f01c3f5c7 Add debugging for strace make_command_line
* 8:  a4cdbece43 =  8:  d43f1eebf2 strace --quiet: be *really* quiet
* 9:  7e52ffd3ba =  9:  0053f7b38e path_conv: special-case root directory to have trailing slash
* 10:  6417ed9cd1 = 10:  1e8a891f5e When converting to a Unix path, avoid double trailing slashes
* 11:  b314cf5603 = 11:  673065dd1e msys2_path_conv: pass PC_NOFULL to path_conv
* 12:  68a1399052 = 12:  e1db14849f path-conversion: Introduce ability to switch off conversion.
* 13:  097d4c1973 = 13:  f6e516da39 dcrt0.cc: Untangle allow_glob from winshell
* 14:  9b7dbd7af9 = 14:  1059fbbdea dcrt0.cc (globify): Don't quote literal strings differently when dos_spec
* 15:  edba1e9a5b = 15:  f8da08fd7e Add debugging for build_argv
* 16:  607001f33d = 16:  03d6fe120a environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL
* 17:  4b69189569 = 17:  90d66ee649 Fix native symbolic link spawn passing wrong arg0
* 18:  245f16540b = 18:  7b84fed8f0 Introduce the `enable_pcon` value for `MSYS`
* 19:  7462e30c92 = 19:  6f87e23bae popen: call /usr/bin/sh instead of /bin/sh
* 20:  37dd55bf4d = 20:  df7a56eeaa Disable the 'cygwin' GitHub workflow
* 21:  41778dfe0f = 21:  cf56ccdb64 CI: add a GHA for doing a basic build test
* 22:  5b7e798c8e = 22:  083c245339 CI: fix the build with gcc 13
* 23:  293731b071 = 23:  91f46dfb4b Set up a GitHub Action to keep in sync with Cygwin
* 24:  15ae7aa902 = 24:  4dd6aad863 Expose full command-lines to other Win32 processes by default
* 25:  ab240c56d0 = 25:  6ef58ed329 Add a helper to obtain a function's address in kernel32.dll
* 26:  ed62ffe5a9 = 26:  38a8880717 Emulate GenerateConsoleCtrlEvent() upon Ctrl+C
* 27:  79f03e1f50 = 27:  b9d1fadafe kill: kill Win32 processes more gently
* 28:  f14b38953e = 28:  715f6ce891 Cygwin: make option for native inner link handling.
* 29:  be6f3f0de4 = 29:  abeeb31b2b docs: skip building texinfo and PDF files
* 30:  eb5833fe48 = 30:  fbe8ae30a3 install-libs: depend on the "toollibs"
* 31:  f384af0be9 = 31:  38abc7cfff POSIX-ify the SHELL variable
* 32:  50cd806fd1 = 32:  9c758e8f9c Handle ORIGINAL_PATH just like PATH
* 33:  5e28622a1a = 33:  312f7660cc uname: allow setting the system name to CYGWIN
* 34:  dacdc1ad16 = 34:  e19af2018e Pass environment variables with empty values
* 35:  8c8e8e90cd = 35:  4deb751587 Optionally disallow empty environment values again
* 36:  310c9bcfe4 = 36:  a1f282d18d build_env(): respect the `MSYS` environment variable
* 37:  9d03af780a = 37:  d1b382b8d6 Revert "Cygwin: Enable dynamicbase on the Cygwin DLL by default"
* 38:  773b5d9065 = 38:  997f6f3ea0 CI: set -Wno-error=maybe-uninitialized
* 39:  3255d4e481 = 39:  e347515e99 Avoid sharing cygheaps across Cygwin versions
* 40:  952a99fc73 = 40:  dd9d970a97 uname: report msys2-runtime commit hash, too
* 41:  9b4cf2936a <  -:  ---------- fixup! Add functionality for changing OS name via MSYSTEM environment variables.

</details>

2024-08-27 16:35 UTC, lazka commented
sure, looks good, thanks.

I'm confused why git rebase dropped that hunk.. there was no conflict.

2024-08-27 16:40 UTC, lazka commented
double checked, and everything else is there at least.

2024-08-27 16:57 UTC, dscho commented
> I'm confused why git rebase dropped that hunk.. there was no conflict.

@lazka Aha! I looked a little bit more closely, and the original change to drop renaming `CYGWIN_DEBUG` to `MSYS_DEBUG` is in 38020a7e0e6a105b9d4bc25e745286014a36d17d, which is marked as a `fixup!` of d1cb51f64425bb111e1f1cf002008642e1abf53f.

However, in that commit, the `CYGWIN_DEBUG` variable was not renamed to `MSYS_DEBUG`, at least not in `winsup/cygwin/environ.cc` (but in `winsup/cygwin/dcrt0.cc`). That was done two patches later, in ed83b2cc2e452756933227abe7a94cf6a5d5f49b.

So when the auto-squash tried to fix up the replayed d1cb51f64425bb111e1f1cf002008642e1abf53f by dropping that hunk, Git realized that the pre-image _already_ had `CYGWIN_DEBUG` and basically thought: hey, this is great, the change was already applied, good, nothing to be done, let's continue. But two patches later, that symbol was renamed to `MSYS_DEBUG` and that's how we ended up here.

2024-08-27 16:58 UTC, merged

2024-08-27 17:17 UTC, lazka commented
Oh, good catch. I kinda would have expected git to complain there somehow, either when doing the wrong fixup or when dropping it later. I need to be more careful next time.